### ISSUE TITLE
Monocle fails to load due to the removal of `stringr::str_join` in `stringr` 1.3.0

### ISSUE THREAD

**Issue by gdario** [cole-trapnell-lab/monocle-release#118]
Dear Monocle team,

Today I installed Monocle on R 3.4.3 without problems, but when I tried to load the package I got the 
message:

`Error: package or namespace load failed for ‘monocle’:
 object ‘str_join’ is not exported by 'namespace:stringr'`

The issue seems to be the presence of `stringr::str_join` in the `NAMESPACE` and in `R/plotting.R` (in the documentation and in the code).  According to the [documentation of `stringr`, release 1.3.0](https://cran.r-project.org/web/packages/stringr/news.html): `Long deprecated str_join(), ignore.case() and perl() have now been removed`. I have replaced the three occurrences of  `str_join` with `str_c` and reinstalled the package, and everything seems to work fine.

All the best

**Comment by saimukund20** [comment]
I am getting the same error. I see you have solved it, but i am not able to understand how to do it. Could you please help me with this

**Comment by gdario** [comment]
Hi @saimukund20 
The error we see is due to the fact that monocle, internally, uses a function that is part of the `stringr` package, which is a dependency of monocle. Monocle calls the function `str_join`, which is part of the `stringr` package, in three places. Unfortunately this function has been deprecated for some time, and now has been removed in the latest version of `stringr`.

The solution I used, detailed below, might be a bit tricky, and will probably not work on a Mac. A simpler solution would probably be to download an older version of `stringr`, for example version 1.2.0. You can find the source code in the [stringr archive](https://cran.r-project.org/src/contrib/Archive/stringr/). I haven't tried myself though.

What I did was to download the source code for the package on [BioConductor](https://bioconductor.org/packages/release/bioc/html/monocle.html) (I used the [source tar.gz](https://bioconductor.org/packages/release/bioc/src/contrib/monocle_2.6.1.tar.gz) file for linux, but if you are using a Mac, this will not work, unfortunately). I have then uncompressed the file, looked for all the occurrences of `str_join`, and it turns out that there are only three. If you use RStudio you can use the command `find_in_files` in the Edit menu. Once this is done, you can rebuild the package with the button "Build and Reinstall" in RStudio.

I hope this helps!

**Comment by saimukund20** [comment]
Reinstalling the older version of stringr helped. Thanks a lot. I use a Mac, so I guess changing the namespace technique would not work.


Thanks,

Sai Mukund.

**Comment by ctrapnell** [comment]
I've just merged @rcannood fixes for this issue into the master and pushed them up to the bioconductor build system as release 3.6.2. You can pull from our GitHub repo now to get the fixes, or they should be available through BioC on the next build.

**Comment by gdario** [comment]
Great! Thanks a lot!

**Comment by DarioS** [comment]
The problem persists for version 2.6.2 according to Bioconductor's build report.

**Comment by brianpenghe** [comment]
@DarioS You type these codes on R to solve the problem:
`install.packages("devtools")

library(devtools)

install_github("cole-trapnell-lab/monocle-release")`

**Comment by cramirezs** [comment]
@brianpenghe It worked for me, thank you!

**Comment by DarioS** [comment]
It should be uploaded to Bioconductor this month, to make it into the release branch.

**Comment by mns1972** [comment]
Dear Team Monocle,
I too seem to be experiencing this issue, which seemingly presents only if I were to install the developer version of Monocle. I use a Mac.
> devtools::install_github("cole-trapnell-lab/monocle-release@develop").

My main preference for this version, over the one in Bioconductor, has been that plotting (e.g. plot_cell_clusters) seems more versatile and one could plot expression of a given marker by size rather than scale_viridis).

Is there another solution to getting this to work please?

Many Thanks

**Comment by Xiaojieqiu** [comment]
Hi @mns1972 
The issue is not fixed in the develop branch. Develop branch right now is pretty behind and I won't recommend to use it, but if you really want, you should `git clone` the develop branch and then replace all `str_join` instances  with `str_c`in the files from the cloned branch and rebuild it and install the package (using `R CMD build the_develop_branch_dir` and `R CMD INSTALL the_build_package_file_name`).
